/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLMyEventCollectionResponseEventRecord.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   myEvent/v1
// Description:
//   This is an API
// Classes:
//   GTLMyEventCollectionResponseEventRecord (0 custom class methods, 2 custom properties)

#import "GTLMyEventCollectionResponseEventRecord.h"

#import "GTLMyEventEventRecord.h"

// ----------------------------------------------------------------------------
//
//   GTLMyEventCollectionResponseEventRecord
//

@implementation GTLMyEventCollectionResponseEventRecord
@dynamic items, nextPageToken;

+ (NSDictionary *)arrayPropertyToClassMap {
  NSDictionary *map = @{
    @"items" : [GTLMyEventEventRecord class]
  };
  return map;
}

@end
