/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLMyEventConstants.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   myEvent/v1
// Description:
//   This is an API

#import "GTLMyEventConstants.h"

// Authorization scope
NSString * const kGTLAuthScopeMyEventUserinfoEmail = @"https://www.googleapis.com/auth/userinfo.email";
