/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLMyEvent_Sources.m
//
// This file can be compiled into projects to avoid adding the individual
// source files for this service.
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   myEvent/v1
// Description:
//   This is an API

/*
#import "GTLMyEventConstants.m"

#import "GTLMyEventCollectionResponseEventRecord.m"
#import "GTLMyEventCollectionResponseString.m"
#import "GTLMyEventEventRecord.m"

#import "GTLQueryMyEvent.m"
#import "GTLServiceMyEvent.m"
 */
