/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLMyEventCollectionResponseString.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   myEvent/v1
// Description:
//   This is an API
// Classes:
//   GTLMyEventCollectionResponseString (0 custom class methods, 2 custom properties)

#import "GTLMyEventCollectionResponseString.h"

// ----------------------------------------------------------------------------
//
//   GTLMyEventCollectionResponseString
//

@implementation GTLMyEventCollectionResponseString
@dynamic items, nextPageToken;

+ (NSDictionary *)arrayPropertyToClassMap {
  NSDictionary *map = @{
    @"items" : [NSString class]
  };
  return map;
}

@end
