/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLMyEvent.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   myEvent/v1
// Description:
//   This is an API

#import "GTLMyEventConstants.h"

#import "GTLMyEventCollectionResponseEventRecord.h"
#import "GTLMyEventCollectionResponseString.h"
#import "GTLMyEventEventRecord.h"

#import "GTLQueryMyEvent.h"
#import "GTLServiceMyEvent.h"
