/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLMyEventEventRecord.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   myEvent/v1
// Description:
//   This is an API
// Classes:
//   GTLMyEventEventRecord (0 custom class methods, 12 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

// ----------------------------------------------------------------------------
//
//   GTLMyEventEventRecord
//

@interface GTLMyEventEventRecord : GTLObject
@property (nonatomic, retain) NSNumber *category;  // intValue

// Remapped to 'descriptionProperty' to avoid NSObject's 'description'.
@property (nonatomic, copy) NSString *descriptionProperty;

@property (nonatomic, copy) NSString *endDate;
@property (nonatomic, copy) NSString *extraContactInfo;
@property (nonatomic, copy) NSString *host;
@property (nonatomic, copy) NSString *hostUrl;
@property (nonatomic, copy) NSString *location;
@property (nonatomic, retain) NSArray *participants;  // of NSString
@property (nonatomic, copy) NSString *startDate;
@property (nonatomic, retain) NSNumber *status;  // intValue
@property (nonatomic, retain) NSNumber *timeStamp;  // longLongValue
@property (nonatomic, copy) NSString *title;
@end
