/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLMyEventCollectionResponseEventRecord.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   myEvent/v1
// Description:
//   This is an API
// Classes:
//   GTLMyEventCollectionResponseEventRecord (0 custom class methods, 2 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

@class GTLMyEventEventRecord;

// ----------------------------------------------------------------------------
//
//   GTLMyEventCollectionResponseEventRecord
//

// This class supports NSFastEnumeration over its "items" property. It also
// supports -itemAtIndex: to retrieve individual objects from "items".

@interface GTLMyEventCollectionResponseEventRecord : GTLCollectionObject
@property (nonatomic, retain) NSArray *items;  // of GTLMyEventEventRecord
@property (nonatomic, copy) NSString *nextPageToken;
@end
